# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bop',
                'doc_host': 'https://ADubinA.github.io',
                'git_url': 'https://github.com/ADubinA/bop',
                'lib_path': 'bop'},
  'syms': {'bop.core': {'bop.core.foo': ('core.html#foo', 'bop/core.py')}}}
